<?php
// DBfiles/db_config.php
// Single source of truth for DB connection values and connection helpers.

// Resolve project root from this file location.
if (!defined('APP_ROOT')) {
    define('APP_ROOT', dirname(__DIR__));
}

// Check if production config exists (generated by GitHub Actions on deployment)
$appConfig = APP_ROOT . '/DBfiles/app_config.php';
$localConfig = APP_ROOT . '/DBfiles/db_local_config.php';

if (file_exists($appConfig)) {
    // === PRODUCTION ENVIRONMENT ===
    // Load production config - this overrides everything
    require_once $appConfig;
    if (!defined('DB_CONFIG_SOURCE')) {
        define('DB_CONFIG_SOURCE', 'production');
    }
} elseif (file_exists($localConfig)) {
    // === LOCAL OVERRIDE ===
    // Personal config file (gitignored) - keeps your passwords out of the repo
    require_once $localConfig;
    if (!defined('DB_CONFIG_SOURCE')) {
        define('DB_CONFIG_SOURCE', 'local_override');
    }
} else {
    // === DEVELOPMENT DEFAULTS ===
    // Default development config (safe for repo)
    define('DB_CONFIG_SOURCE', 'development');
    define('BASE_PATH', '');
    define('DB_HOST', '3.142.11.187');
    define('DB_PORT', 3306);
    define('DB_USER', 'root');
    define('DB_PASS', 'twlbiVY=cUn4');
    define('DB_NAME', 'oppilot');
}

/**
 * Create a mysqli connection using shared config constants.
 */
function getDbConnection($exitOnError = true) {
    $conn = null;
    $exceptionMessage = '';
    $hostPort = DB_HOST . ':' . (int)DB_PORT;

    try {
        $conn = mysqli_init();
        if ($conn) {
            $conn->options(MYSQLI_OPT_CONNECT_TIMEOUT, 5);
            $conn->real_connect(DB_HOST, DB_USER, DB_PASS, DB_NAME, (int)DB_PORT);
        }
    } catch (Throwable $e) {
        $exceptionMessage = $e->getMessage();
    }

    if (!$conn || $conn->connect_error) {
        $msg = 'Database connection failed (' . $hostPort . ')';
        if ($exceptionMessage !== '') {
            $msg .= ': ' . $exceptionMessage;
        } elseif ($conn && $conn->connect_error) {
            $msg .= ': ' . $conn->connect_error;
        }
        if ($exitOnError) {
            http_response_code(503);
            die(json_encode([
                'success' => false,
                'error' => $msg
            ]));
        }
        return null;
    }

    $conn->set_charset('utf8mb4');
    return $conn;
}

// Test connection function (optional - for debugging)
function testConnection() {
    try {
        $conn = getDbConnection();
        return [
            'success' => true,
            'message' => 'Database connection successful!',
            'database' => DB_NAME,
            'port' => DB_PORT
        ];
    } catch (Exception $e) {
        return [
            'success' => false,
            'error' => $e->getMessage()
        ];
    }
}
?>